@startuml

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Storage/all.puml

skinparam NoteShadowing true
skinparam NoteBackgroundColor lightyellow
skinparam RectangleBorderColor #blue
skinparam nodesep 50

rectangle "<size:18><color:#blue>us-east-1a" as 1a {
  EC2Instance(ec1, "", "")
  ElasticBlockStoreVolume(ebs1, "EBS\n(50 GB)", "")
}

rectangle "<size:18><color:#blue>us-west-1b" as 1b {
  EC2Instance(ec2, "", "")
  ElasticBlockStoreVolume(ebs2, "EBS\n(50 GB)", "")
}

note top of 1b : <b>Restored into\ndifferent Zone & Region

ElasticBlockStoreSnapshot(snp, "EBS\nSnapshot","")

ebs1 -u-> ec1
ebs2 -u-> ec2

ebs1 -r-> snp : <b>snapshot
snp -r-> ebs2 : <b>restore

@enduml