skinparam roundcorner 5
'skinparam linetype ortho
skinparam shadowing false
skinparam handwritten false
skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}
hide empty members

skinparam defaultFontName       "Verdana"
skinparam defaultFontSize       12
skinparam dpi                   110
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    40
skinparam BoxPadding            40
skinparam Padding               5

!define optional(x) <b><color:#b8861b><&question></color> x</b>
